import datetime
from wtforms import Form, BooleanField, StringField, SelectField, PasswordField, validators
from google.appengine.ext import ndb

class Record(ndb.Model):
  created_at = ndb.DateTimeProperty(required=True, auto_now_add=True)
  record_id = ndb.StringProperty()
  parent_record_id = ndb.StringProperty()
  parent_page_id = ndb.StringProperty()
  parent_element_id = ndb.StringProperty()
  created_date = ndb.StringProperty()
  created_by = ndb.StringProperty()
  created_location = ndb.StringProperty()
  created_device_id = ndb.StringProperty()
  modified_date = ndb.StringProperty()
  modified_by = ndb.StringProperty()
  modified_location = ndb.StringProperty()
  modified_device_id = ndb.StringProperty()
  server_modified_date = ndb.StringProperty()
  si_autre_precisez_ = ndb.StringProperty()
  soins_de_sant_communautaires_informels = ndb.StringProperty()
  soins_de_sant_primaire = ndb.StringProperty()
  si_oui_prciser__plusieurs_rponses_possibles = ndb.StringProperty()
  soins_psychiatriques = ndb.StringProperty()
  soins_psychologiques = ndb.StringProperty()
  relation_daide = ndb.StringProperty()
  counseling = ndb.StringProperty()
  precisez2 = ndb.StringProperty()
  autre_petita = ndb.StringProperty()
  preciser_autres = ndb.StringProperty()
  sant_communautaires = ndb.StringProperty()
  santprimaire2 = ndb.StringProperty()
  soins_de_counseling = ndb.StringProperty()

  soins_sante_psychologiques2 = ndb.StringProperty()
  soins_santepsychiatriques3 = ndb.StringProperty()
  grille_tarifaire_relation3 = ndb.StringProperty()
  combien_mensuellement = ndb.StringProperty()
  pour_quelles_raisons = ndb.StringProperty()
  approx_precisez = ndb.StringProperty()
  comment_publicisez = ndb.StringProperty()
  precisez_autres2 = ndb.StringProperty()
  a = ndb.StringProperty()
  b = ndb.StringProperty()
  c = ndb.StringProperty()
  d = ndb.StringProperty()
  otre_precisez = ndb.StringProperty()
  catgories_denfants_vulnrables_que_vous_recevez = ndb.StringProperty()
  autre_categorie = ndb.StringProperty()
  dcrire_les_catgories_dintervenants_ = ndb.StringProperty()
  autre_categorie_intervenants = ndb.StringProperty()
  autres_categories_precisez = ndb.StringProperty()
  endroits_formation_precisez_autres = ndb.StringProperty()
  autres_endroit_de_suivi_formation = ndb.StringProperty()
  quels_organismes_vous_rfrez_les_demandes = ndb.StringProperty()
  organisme_relation_de_formation = ndb.StringProperty()
  organisme_relation_dchanges_de_pratique = ndb.StringProperty()
  autres_organismes_relations = ndb.StringProperty()
  obstacles_rencontre_dispensation_services = ndb.StringProperty()
  autres_obstacles_precisez = ndb.StringProperty()
  obstacles_rencontre_par_patients = ndb.StringProperty()
  si_oui_savezvous_pourquoi = ndb.StringProperty()

  demandes_pas_de_specialites = ndb.StringProperty()
  connaissezvous_gens_communaute_formation_academik = ndb.StringProperty()
  estce_que_votre_organisation_offre_des_services_en_sant_men = ndb.StringProperty()
  sant_communautaires_informels = ndb.StringProperty()
  sant_primaire = ndb.StringProperty()
  counseling2 = ndb.StringProperty()
  soins_psychologiques2 = ndb.StringProperty()
  psychiatriques2 = ndb.StringProperty()
  nombres_de_demandes = ndb.StringProperty()
  relation_daide2 = ndb.StringProperty()
  c_estce_que_les_services_sont_gratuits__ = ndb.StringProperty()
  approximation_de_la_distance = ndb.StringProperty()
  refuser_des_demandes = ndb.StringProperty()
  autre_centre_offrant_des_services = ndb.StringProperty()
  recevezvous_des_enfants_vulnrables_ou_leurs_parents = ndb.StringProperty()
  formations_en_sant_mentale_amliorer_comptences = ndb.StringProperty()
  nombre_intervenants_travaillant = ndb.StringProperty()

  commune = ndb.StringProperty()
  departement = ndb.StringProperty()
  adresse = ndb.StringProperty()
  nom_de_lorganisation = ndb.StringProperty()
  gps_ = ndb.StringProperty()
  telephone = ndb.StringProperty()
  personne_de_contact = ndb.StringProperty()
  email = ndb.StringProperty()
  site_web = ndb.StringProperty()

  type_plusieurs_rponses_possibles = ndb.StringProperty()
  statut = ndb.StringProperty()
  jour = ndb.StringProperty()
  heure = ndb.StringProperty()
  precisez_autres_sources_financements = ndb.StringProperty()
  my_element14 = ndb.StringProperty()
  precisez_type_organisme = ndb.StringProperty()
  source_de_financement = ndb.StringProperty()
  niveau_de_formation_intervenants = ndb.StringProperty()
  quel_endroit = ndb.StringProperty()
  autre_status = ndb.StringProperty()
  les_principaux_motifs_de_consultation_plusieurs_rponses_possib = ndb.StringProperty()
  preciser_autres_motifs_consultation = ndb.StringProperty()
  types_de_thrapie_utiliss_plusieurs_rponses_possibles = ndb.StringProperty()
  si_autres_precisez_types_de_therapie = ndb.StringProperty()
  globalement__combien_estimezvous_le_cot_annuel_de_ces_servic = ndb.StringProperty()
  prcisez_leur_groupe_dge = ndb.StringProperty()

  services_sontils_disponibles_pour_les_enfants_vulnrables = ndb.StringProperty()
  activits_socioculturelles = ndb.StringProperty()
  mdication = ndb.StringProperty()
  activits_psychosociales = ndb.StringProperty()
  psychanalyse = ndb.StringProperty()
  accompagnement_psychosocial = ndb.StringProperty()
  musicothrapie = ndb.StringProperty()
  club_denfants = ndb.StringProperty()
  niveau_de_formation_intervenants = ndb.StringProperty()
  psychoducation = ndb.StringProperty()
  thrapie_par_le_thtre = ndb.StringProperty()
  thrapie_corporelle = ndb.StringProperty()
  thrapie_cognitive_et_comportementale = ndb.StringProperty()
  autres = ndb.StringProperty()
  si_vous_referez_precisez_ou = ndb.StringProperty()
  quels_sont_les_organismes_qui_vous_rfrent_des_demandes_ = ndb.StringProperty()
  de_rfrencement = ndb.StringProperty()

  votre_organisation_offre_des_services_de_types_psychosociaux = ndb.StringProperty()
  si_oui_preciser_types_de_services_psycho = ndb.StringProperty()
  precisez_autres_types_services_psycho = ndb.StringProperty()
  connaissezvous_centre_offrant_des_services_sante = ndb.StringProperty()
  question_a = ndb.StringProperty()
  question_b = ndb.StringProperty()
  question_c = ndb.StringProperty()
  question_d = ndb.StringProperty()

  latitude = ndb.StringProperty()
  longitude = ndb.StringProperty()


def save(self, form, LEGACY_TEMPLATE):
  record = Record()
  form.populate_obj(record)
  record.put()
  self.redirect("/records/{0}/edit?message={1}".format(record.key.id(), "Profile updated successfully"))

def update(self, TEMPLATE, form, record_key):
  record = Record.get_by_id(int(record_key))
  form.populate_obj(record)
  if record.put():
    record_dict = {
      "test": "test"
    }
    #user_json = json.dumps(user_dict)
    #user_audit = Audit.save(initiated_by = self.session.get("user"), user_affected = user.email, security_clearance = "admin", json_data = user_json, model= "User", action = "Update User")
    #profile_update_email(user.email)

    if record_key:
      self.redirect("/records/{0}/edit?message={1}".format(record_key, "Profile updated successfully"))
    else:
      self.redirect("/users/profile?message={0}".format("Profile updated successfully"))
  else:
    self.response.write(TEMPLATE.render({"form": form, "message": "Profile unsuccessful. Please contact administrator."}))


class RecordForm(Form):
  si_autre_precisez_ = StringField('Si Autre Precisez', [validators.Length(min=0, max=100)])
  soins_de_sant_communautaires_informels = StringField('Soins De Sand Sommunautaires Informels', [validators.Length(min=0, max=100)])
  soins_de_sant_primaire = StringField('Soins De Sant Primaire', [validators.Length(min=0, max=100)])
  si_oui_prciser__plusieurs_rponses_possibles = StringField('Si Oui Prciser Plusieurs Rponses Possibles', [validators.Length(min=0, max=100)])
  soins_psychiatriques = StringField('Soins Psychiatriques', [validators.Length(min=0, max=100)])
  soins_psychologiques = StringField('Soins Psychologiques', [validators.Length(min=0, max=100)])
  relation_daide = StringField('Relation Daide', [validators.Length(min=0, max=100)])
  counseling = StringField('Counseling', [validators.Length(min=0, max=100)])
  precisez2 = StringField('Precisez2', [validators.Length(min=0, max=100)])
  autre_petita = StringField('Autre Petita', [validators.Length(min=0, max=100)])
  preciser_autres = StringField('Preciser Autres', [validators.Length(min=0, max=100)])
  sant_communautaires = StringField('Sant Communautaires', [validators.Length(min=0, max=100)])
  santprimaire2 = StringField('Sant Primaire2', [validators.Length(min=0, max=100)])
  soins_de_counseling = StringField('Soins De Counseling', [validators.Length(min=0, max=100)])

  soins_sante_psychologiques2 = StringField('Soins Sante Psychologiques', [validators.Length(min=0, max=100)])
  soins_santepsychiatriques3 = StringField('Soins Sane Psychiatriques3', [validators.Length(min=0, max=100)])
  grille_tarifaire_relation3 = StringField('Grille Tarifaire Relation3', [validators.Length(min=0, max=100)])
  combien_mensuellement = StringField('Combien Mensuellement', [validators.Length(min=0, max=100)])
  pour_quelles_raisons = StringField('Pour quelles raisons', [validators.Length(min=0, max=100)])
  approx_precisez = StringField('Approx Precisez', [validators.Length(min=0, max=100)])
  comment_publicisez = StringField('Comment Publicisez', [validators.Length(min=0, max=100)])
  precisez_autres2 = StringField('Precisez Autres2', [validators.Length(min=0, max=100)])
  a = StringField('A', [validators.Length(min=0, max=100)])
  b = StringField('B', [validators.Length(min=0, max=100)])
  c = StringField('C', [validators.Length(min=0, max=100)])
  d = StringField('D', [validators.Length(min=0, max=100)])
  otre_precisez = StringField('Otre Precisez', [validators.Length(min=0, max=100)])
  catgories_denfants_vulnrables_que_vous_recevez = StringField('Categories Denfants Vulnrables Que Vous Receves', [validators.Length(min=0, max=100)])
  autre_categorie = StringField('Autre Categorie', [validators.Length(min=0, max=100)])
  dcrire_les_catgories_dintervenants_ = StringField('Dcrire Les Catgories Dintervenants', [validators.Length(min=0, max=100)])
  autre_categorie_intervenants = StringField('Autre Categorie Intervenants', [validators.Length(min=0, max=100)])
  autres_categories_precisez = StringField('Autre Categorie Precisez', [validators.Length(min=0, max=100)])
  endroits_formation_precisez_autres = StringField('Endroits Formation Precisez Autres', [validators.Length(min=0, max=100)])
  autres_endroit_de_suivi_formation = StringField('Autres Endroid De Suivi Formation', [validators.Length(min=0, max=100)])
  quels_organismes_vous_rfrez_les_demandes = StringField('Quels Organismes Vous Rfrez Les Demandes', [validators.Length(min=0, max=100)])
  organisme_relation_de_formation = StringField('Organisme Relation De Formation', [validators.Length(min=0, max=100)])
  organisme_relation_dchanges_de_pratique = StringField('organisme Relation Dchanges De Praqtique', [validators.Length(min=0, max=100)])
  autres_organismes_relations = StringField('Autres Organismes Relations', [validators.Length(min=0, max=100)])
  obstacles_rencontre_dispensation_services = StringField('Obstacles Rencontre Dispensation Services', [validators.Length(min=0, max=100)])
  autres_obstacles_precisez = StringField('Autres Obstacles Precisez', [validators.Length(min=0, max=100)])
  obstacles_rencontre_par_patients = StringField('Obstacles Rencontre Par Patients', [validators.Length(min=0, max=100)])
  si_oui_savezvous_pourquoi = StringField('Si Oui Savezvous Pourquoi', [validators.Length(min=0, max=100)])

  demandes_pas_de_specialites = StringField('Demandes Pas De Specialites', [validators.Length(min=0, max=100)])
  connaissezvous_gens_communaute_formation_academik = StringField('Connaissezvous Gens Communaute Formation Academik', [validators.Length(min=0, max=100)])
  estce_que_votre_organisation_offre_des_services_en_sant_men = StringField('Estce Que Votre Organisation Offre Des Services En Sant Men', [validators.Length(min=0, max=100)])
  sant_communautaires_informels = StringField('Sant Communautaires Informels', [validators.Length(min=0, max=100)])
  sant_primaire = StringField('Sant Primaire', [validators.Length(min=0, max=100)])
  counseling2 = StringField('Counseling2', [validators.Length(min=0, max=100)])
  soins_psychologiques2 = StringField('Soins Psychologiques2', [validators.Length(min=0, max=100)])
  psychiatriques2 = StringField('Psychologiques2', [validators.Length(min=0, max=100)])
  nombres_de_demandes = StringField('Nombres De Demandes', [validators.Length(min=0, max=100)])
  relation_daide2 = StringField('Relation Daide2', [validators.Length(min=0, max=100)])
  c_estce_que_les_services_sont_gratuits__ = StringField('C Estce Que Les Services Sont Gratuits', [validators.Length(min=0, max=100)])
  approximation_de_la_distance = StringField('Approximation De La Distance', [validators.Length(min=0, max=100)])
  refuser_des_demandes = StringField('Refuser Des Demandes', [validators.Length(min=0, max=100)])
  autre_centre_offrant_des_services = StringField('Autre Centre Offrant Des Services', [validators.Length(min=0, max=100)])
  recevezvous_des_enfants_vulnrables_ou_leurs_parents = StringField('Recevezvous Des Enfants Vulnrables Ou Luers Parents', [validators.Length(min=0, max=100)])
  formations_en_sant_mentale_amliorer_comptences = StringField('Formations En Sant Mentale Amliorer Comtences', [validators.Length(min=0, max=100)])
  nombre_intervenants_travaillant = StringField('Nobre Intervenants Travaillant', [validators.Length(min=0, max=100)])

  commune = StringField('Commune', [validators.Length(min=0, max=100)])
  departement = StringField('Department', [validators.Length(min=0, max=100)])
  adresse = StringField('Adresse', [validators.Length(min=0, max=100)])
  nom_de_lorganisation = StringField('Nom De Lorganisation', [validators.Length(min=0, max=100)])
  telephone = StringField('Telephone', [validators.Length(min=0, max=100)])
  personne_de_contact = StringField('Personne De Contact', [validators.Length(min=0, max=100)])
  email = StringField('Email', [validators.Length(min=0, max=100)])
  site_web = StringField('Site Web', [validators.Length(min=0, max=100)])

  type_plusieurs_rponses_possibles = StringField('Type Plusieurs Rponses Possibles', [validators.Length(min=0, max=100)])
  statut = StringField('Statut', [validators.Length(min=0, max=100)])
  jour = StringField('Jour', [validators.Length(min=0, max=100)])
  heure = StringField('Huere', [validators.Length(min=0, max=100)])
  precisez_autres_sources_financements = StringField('Precisez Autres Sources Financements', [validators.Length(min=0, max=100)])
  my_element14 = StringField('My Element14', [validators.Length(min=0, max=100)])
  precisez_type_organisme = StringField('Precisez Type Organisme', [validators.Length(min=0, max=100)])
  source_de_financement = StringField('Source De Financement', [validators.Length(min=0, max=100)])
  niveau_de_formation_intervenants = StringField('Niveau De Formation Intervenants', [validators.Length(min=0, max=100)])
  quel_endroit = StringField('Quel Endroit', [validators.Length(min=0, max=100)])
  autre_status = StringField('Autre Status', [validators.Length(min=0, max=100)])
  les_principaux_motifs_de_consultation_plusieurs_rponses_possib = StringField('Les Principaux Motifs De Consultation Plusiers Rponses Possib', [validators.Length(min=0, max=100)])
  preciser_autres_motifs_consultation = StringField('Preciser Autres Motifs Consultation', [validators.Length(min=0, max=100)])
  types_de_thrapie_utiliss_plusieurs_rponses_possibles = StringField('Types De Therapie Utiliss Plusieurs Rponses Possibles', [validators.Length(min=0, max=100)])
  si_autres_precisez_types_de_therapie = StringField('Si Autres Precisez Types De Therapie', [validators.Length(min=0, max=100)])
  globalement__combien_estimezvous_le_cot_annuel_de_ces_servic = StringField('Globalement Combien Esimezvous Le Cot Annuel De Ces Servic', [validators.Length(min=0, max=100)])
  prcisez_leur_groupe_dge = StringField('Prcisez Leur Groupe Dge', [validators.Length(min=0, max=100)])

  services_sontils_disponibles_pour_les_enfants_vulnrables = StringField('Services Sontils Disponibles Pour Les Enfants Vulnrables', [validators.Length(min=0, max=100)])
  activits_socioculturelles = StringField('Activits Socioculturelles', [validators.Length(min=0, max=100)])
  mdication = StringField('Mdcation', [validators.Length(min=0, max=100)])
  activits_psychosociales = StringField('Activits Psychosociales', [validators.Length(min=0, max=100)])
  psychanalyse = StringField('Psychanalyse', [validators.Length(min=0, max=100)])
  accompagnement_psychosocial = StringField('Accompagnement Psychosocial', [validators.Length(min=0, max=100)])
  musicothrapie = StringField('Musicothrapie', [validators.Length(min=0, max=100)])
  club_denfants = StringField('Club Denfants', [validators.Length(min=0, max=100)])
  niveau_de_formation_intervenants = StringField('Niveau De Formation Intervenants', [validators.Length(min=0, max=100)])
  psychoducation = StringField('Psychoducation', [validators.Length(min=0, max=100)])
  thrapie_par_le_thtre = StringField('Thrapie Par Le Thtre', [validators.Length(min=0, max=100)])
  thrapie_corporelle = StringField('Thrapie Corporelle', [validators.Length(min=0, max=100)])
  thrapie_cognitive_et_comportementale = StringField('Thrapie Cognitive Et Comportementale', [validators.Length(min=0, max=100)])
  autres = StringField('Autres', [validators.Length(min=0, max=100)])
  si_vous_referez_precisez_ou = StringField('Si Vous Referez Precisez Ou', [validators.Length(min=0, max=100)])
  quels_sont_les_organismes_qui_vous_rfrent_des_demandes_ = StringField('Quels Sont Les Organismes Qui Vous Rfrent Des Demandes', [validators.Length(min=0, max=100)])
  de_rfrencement = StringField('De Rfrencement', [validators.Length(min=0, max=100)])

  votre_organisation_offre_des_services_de_types_psychosociaux = StringField('Votre Organisation Offre Des Services De Types Psychosociaux', [validators.Length(min=0, max=100)])
  si_oui_preciser_types_de_services_psycho = StringField('Si Oui Preciser Types De Services Psycho', [validators.Length(min=0, max=100)])
  precisez_autres_types_services_psycho = StringField('Precisez Autres Types Services Psycho', [validators.Length(min=0, max=100)])
  connaissezvous_centre_offrant_des_services_sante = StringField('Connaissezvous Centre Offrant Des Services Sant', [validators.Length(min=0, max=100)])
  question_a = StringField('Question A', [validators.Length(min=0, max=100)])
  question_b = StringField('Question B', [validators.Length(min=0, max=100)])
  question_c = StringField('Question C', [validators.Length(min=0, max=100)])
  question_d = StringField('Question D', [validators.Length(min=0, max=100)])
